### PR TITLE
Add Nim runtime

### PR DESCRIPTION
**Pull request by mhart**
(also cleaned up some redundant "runtime"s)

Wasn't sure if you'd prefer all binary compilation languages at the top or not? If so, I can shift Nim up

### CODE REVIEW

**Comment by mthenw** [comment]
I was thinking about alphabetic order with the official at the top. Can you move up Nim before Node?

**Comment by mhart** [comment]
Ah yeah, makes sense, will do 👍

**Comment by mhart** [comment]
Done!

**Comment by mthenw** [comment]
Awesome, thanks!

**Pull request merged**
